SYNCQT.HEADER_FILES = qftp.h qurlinfo.h 
SYNCQT.GENERATED_HEADER_FILES = QFtp QUrlInfo qtftpversion.h QtFtpVersion QtFtp 
SYNCQT.PRIVATE_HEADER_FILES = 
SYNCQT.QPA_HEADER_FILES = 
SYNCQT.CLEAN_HEADER_FILES = qftp.h qurlinfo.h 
SYNCQT.INJECTIONS = 
